rock_artists = [
    "The Beatles",
    "Led Zeppelin",
    "The Rolling Stones",
    "Pink Floyd",
    "Queen",
    "AC/DC",
    "U2",
    "Nirvana",
    "Guns N' Roses",
    "The Who",
    "Jimi Hendrix",
    "Bruce Springsteen",
    "Aerosmith",
    "The Eagles",
    "Metallica",
    "Black Sabbath",
    "The Doors",
    "David Bowie",
    "Fleetwood Mac",
    "Bob Dylan",
    "The Beach Boys",
    "Bon Jovi",
    "Radiohead",
    "Van Halen",
    "Pearl Jam",
    "Red Hot Chili Peppers",
    "Rush",
    "Deep Purple",
    "Creedence Clearwater Revival",
    "The Clash",
    "Santana",
    "Lynyrd Skynyrd",
    "Oasis",
    "The Police",
    "The Kinks",
    "ZZ Top",
    "Journey",
    "Foo Fighters",
    "Cream",
    "Queen",
    "The Jimi Hendrix Experience",
    "The Smiths",
    "Stevie Ray Vaughan",
    "The Cure",
    "Genesis",
    "The Ramones",
    "Green Day",
    "R.E.M.",
    "The Byrds",
    "The Velvet Underground",
    "Talking Heads",
    "The Strokes",
    "Radiohead",
    "Arctic Monkeys",
    "Soundgarden",
    "The White Stripes",
    "The Black Keys",
    "Kings of Leon",
    "Coldplay",
    "The Smashing Pumpkins",
    "Alice Cooper",
    "Def Leppard",
    "The Allman Brothers Band",
    "Iron Maiden",
    "Motorhead",
    "Jethro Tull",
    "Judas Priest",
    "Pantera",
    "Linkin Park",
    "Nickelback",
    "Creed",
    "Slipknot",
    "KISS",
    "The Yardbirds",
    "Steppenwolf",
    "Bad Company",
    "The Byrds",
    "The Animals",
    "The Zombies",
    "The Monkees",
    "The Temptations",
    "The Supremes",
    "The Miracles",
    "The Four Tops",
    "The Beach Boys",
    "The Drifters",
    "The Everly Brothers",
    "The Righteous Brothers",
    "The Marvelettes",
    "The Shirelles",
    "The Coasters",
    "The Isley Brothers",
    "The Ronettes",
    "The Crystals",
    "The Chiffons",
    "The Platters",
    "The Ink Spots",
    "The Orioles",
    "The Penguins",
    "The Flamingos"
]
